export TZ='UTC'
# claude code env vars
export CLAUDE_CODE_DISABLE_NONSTRICT_PARAMS=1
export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1
export CLAUDE_CODE_DISABLE_FEEDBACK_SURVEY=1
export CLAUDE_CODE_SKIP_PROMPT_HISTORY=1
export CLAUDE_CODE_DISABLE_AUTO_MEMORY=1
export CLAUDE_CODE_DISABLE_GIT_INSTRUCTIONS=1
export CLAUDE_CODE_AUTO_UPDATE=false
# put the global env