[Unit]
Description=Blocky DNS Proxy
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=YOU_KNOW_WHO
ExecStart=%h/repo/blocky/blocky --config %h/repo/blocky/config.yaml
Restart=on-failure
RestartSec=5s
ExecReload=/usr/bin/curl -sS -X POST http://localhost:4000/api/lists/refresh
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
